### ISSUE TITLE
First Project: Sentiment Analysis Sonification

### ISSUE THREAD

**Issue by MBJean** [dhmit/sonification#1]
# Overview
This project has begun as a blank, boilerplated Django and React web application. Our first challenge will be to implement the following user story.

As a user, I can:
- Enter arbitrary text into an input field and click 'Generate Sonification' (vel sim.).
- Have a basic sentiment analysis performed on the input text.
- Have the data structured produced by that sentiment analysis translated into an audio representation.
- Receive back that audio representation that I can listen to from the web application's front end.

The specifics of each step are up to each team to implement, as is the precise nature of the sonification created. 

## Helpful links
- The Wikipedia entry with a basic definition and examples of sonification: https://en.wikipedia.org/wiki/Sonification
- An MIT writeup of "Spider's Canvas," "an exploration that sonifies the threads of a spider web:" https://news.mit.edu/2019/spider-web-music-inspiring-harmony-art-and-science-0108
- A general introduction to making sound in Python: https://towardsdatascience.com/music-in-python-2f054deb41f4
- A quickstart guide for the `simpleaudio` package, a Python package that we'll start with (but by no means what we'll necessarily end with): https://simpleaudio.readthedocs.io/en/latest/tutorial.html
- An introduction to sentiment analysis using the `nltk` package: https://realpython.com/python-nltk-sentiment-analysis/

**Comment by ryaanahmed** [comment]
Done via #4 #2  etc. -- great work summer team!
