### ISSUE TITLE
Synthesizing Sounds from Polygons 

### ISSUE THREAD

**Issue by vedadehhc** [dhmit/sonification#24]
We will aim to create a function which takes as input a polygon (defined by angles and lengths of sides) and maps it to a sound which is representative of the shape. This is a first step towards analyzing more complex images, in which perhaps shapes could be identified and then sonified individually.

Features:
- Polygon editor on the UI
- Quantify and organize the inputted polygon by side lengths and angles between sides
- Synthesize the angle and length data into sound, perhaps by mapping features of the polygon to specific sound features (e.g. frequency, amplitude, etc.). 
- Experiment with playing sounds for all vertices together, sequentially, or with some combination of overlapping sounds.

We plan to experiment with the synthesis process and the exact mapping of polygon features to sound features.

**Comment by awu482519** [comment]
help :(

**Comment by ryaanahmed** [comment]
closed via #40 and #53
