### ISSUE TITLE
Sonify the shape of text

### ISSUE THREAD

**Issue by jlin00** [dhmit/sonification#25]
We will create an interface for users to upload a text file, transform the shape of the text file (e.g. in terms of whitespace and newlines) and then use the transformed text to generate sound. *(Note: see example of an interesting text shape below.)*

Minimum Viable Product:
- a function to sonify newlines and whitespaces based on properties such as quantity, distance to other characters...etc.
- three functions to transform the shape of a text in JavaScript
- edit the existing text signification page to allows users to input text, transform its shape using buttons, and then convert the transformed text to sound 

Stretch goals:
- display uploaded text in editable text box, allowing users more control over the shape of text 
- additional functions to transform the shape of a text

![image](https://user-images.githubusercontent.com/32581270/134425785-176cfd76-48dd-4ca2-b25b-a99cd96255c7.png)

**Comment by ryaanahmed** [comment]
Hey we got all the stretch goals! Cool. Closed via #44
