### ISSUE TITLE
Synthesize Sound from Cursor Movements

### ISSUE THREAD

**Issue by phuang00** [dhmit/sonification#27]
We will create an interface that allows users to make mouse gestures and create sounds based on the movements (in a similar way to how theremins work).

Minimum Viable Product
- a canvas for users to draw their mouse gestures
- vertical movements dictate the volume
- horizontal movements dictate the pitch
- allow users to choose the sound range, instruments (before/after drawing)

If there's time
- allow users to save previous melodies/sounds and layer new sounds on top of it 
- synchronously produce sound as user moves the cursor
- show which gestures map to which sounds

@ryaanahmed @anastasia

**Comment by ryaanahmed** [comment]
Calling this done via #48
