### ISSUE TITLE
Time Series Data into Sound

### ISSUE THREAD

**Issue by YifanWang0** [dhmit/sonification#28]
As a first step, we will create an interface that will take in a CSV file with time series data to be turned into sound.

Minimum Viable Product: 
- User drops a CSV of size (n,m) to make m sounds
- Currently we can make a single sound with an input of size n; we want to extend this to make m sounds with an array of size (n,m)
- Chain sounds together to create sound that varies over time
- Some questions we will explore:
    - How can we go further than existing automatic music generators?
         - Playing with the time between successive frames
         - Parametrizing types of crossfades 
        
Further Expansion:
- Exploring different types of time-variant data
    - Turn accelerometer data
    - a recording of  x, y, and z accelerations from a gesture
    - Dance choreograph/body movement => sound/music
    - Video recording
    - Weather patterns
    - Stock data

@ryaanahmed @anastasia

**Comment by anastasia** [comment]
Looks great to me. 
One statement I'm confused by is this: "Chain sounds together to see how it is like one the other"? Maybe a typo?

**Comment by ryaanahmed** [comment]
calling initial work closed by #38
