### ISSUE TITLE
Color Encoding to Sound

### ISSUE THREAD

**Issue by MasterEchez** [dhmit/sonification#29]
We will make an interface where a user can play around with RGB sliders, where each slider corresponds to a specific frequency range. As the user is manipulating the sliders, the sound will be produced and a square or the background color will indicate the resulting color combination of the three sliders.

Minimum Viable Product:
- The background or a square indicates the color as you’re sliding the RGB scales
- Three sliders, RGB
- Accessible UI
- Frequency changes as the color values change and each slider would have a specific range of frequencies.

Some questions we will explore:
- How do we choose what sounds are associated with what colors?
-   What ranges of frequencies will we represent in our MVP?
-   Synesthesia
-   How can we show the combination of colors?

Further Expansion:
- Have the RGB sliders manipulate a sound that the user uploads
- Explore other methods of color “encoding”:
        - Hex
        - Color wheel
        - Energy of a picture
        - Pixel intensity
        - Gradients (of a single color or multiple)
                - For example, a user picks two colors and we generate sound based on the gradient
- Canvas where the user draws with different colors

@ryaanahmed @anastasia

**Comment by anastasia** [comment]
Would be interested (further down the road) to see an image manipulated with RGB values (like you can do in photo apps/photoshop). For instance, how does this image sound when it's more blue and less red?

**Comment by ryaanahmed** [comment]
Lots of possibilities still to explore, but calling this initial phase done via #52
