### ISSUE TITLE
Building a Drawing Input Interface

### ISSUE THREAD

**Issue by phuang00** [dhmit/sonification#6]
We will create an interface for users to create their own drawing or upload a photo and then we will use the drawing/photo to generate sound.

Minimum Viable Product:
- Frontend interface for users to draw/erase with one color
- Convert the drawing into a numpy array and process it to create sound to return to the user

If we have time:
- Introduce colors to the drawing canvas
- Modify interface to also allow for uploading photos
- Explore OpenCV and other libraries to analyze the drawings/photos in different perspectives

**Comment by ryaanahmed** [comment]
Done via #12
