### ISSUE TITLE
Build a sound toolkit with FX modules

### ISSUE THREAD

**Issue by joshfeli** [dhmit/sonification#7]
The ways in which we process user input to create sound depends on the tools that we have available. With the creation of some FX functions to modify input soundwaves, we can allow for greater flexibility and creativity in the audio that we produce from user input. We plan to start with the following functions:

- [x] Raising or lowering the "volume" of a wave (affecting its amplitude)
- [x] Speeding up/slowing down audio
- [x] Adding chords to a sequence of notes
- [ ] Overlapping the notes in a sequence

We would also have to ensure that we have a consistent data structure for these waveforms, which will likely be the format Team 2 uses as a return value for its analysis functions (maybe a `bytes` or `bytearray`?).

**Comment by farooqashar** [comment]
amplitude: y = A * np.sin(...) => change A

changing pitch: y = A * np.sin(2* pi * T * freq) => change freq(high freq => higher pitch)

sound quality: change sample rate (high sample rate => more accurate and detailed sound representation)

combine two audio waves: Add y_1 + y_2 as the note where y1 = A * np.sin(...) and y2= A * np.sin(...) **[?]**

duration of audio: length of the notes array

chords: add bunch of notes together

**Comment by joshfeli** [comment]
Draft implementations for these filters (all but `overlap_notes` were implemented with PR #10. See Issue #9 for future improvements.

**Comment by ryaanahmed** [comment]
Closing here because all but one filter on the list completed: we can revisit and decide what filters to implement moving forward.
